import React from 'react';

// Drag'n'drop: immutably reorders an array by moving the item from
// startIndex to endIndex (same algorithm as the official
// react-beautiful-dnd/@hello-pangea/dnd example).
export function reorder(list, startIndex, endIndex) {
  const result = Array.from(list);
  const [removed] = result.splice(startIndex, 1);
  result.splice(endIndex, 0, removed);
  return result;
}

// Unlike HTML/htmltools, React requires the `style` prop to be an object
// (`{color: 'red'}`), not a CSS string (`"color: red;"`) — passing a string
// makes React fail with a confusing error ("Failed to set an indexed
// property... CSSStyleDeclaration"). Since writing `style = "color:
// red;"` in R is a very natural habit (that's how it works with regular
// htmltools tags), it is converted automatically: same approach used by
// shiny.react (`styleStringToObject`).
export function styleStringToObject(styleString) {
  const style = {};
  styleString.split(';').forEach((declaration) => {
    const match = declaration.match(/^\s*([\w-]+)\s*:(.*)$/);
    if (match) {
      const [, name, value] = match;
      style[name.toLowerCase()] = value.trim();
    }
  });
  return style;
}

// Factory for buildElement()/buildProps(), parameterized on the component
// registry (`components`): keeps the {type, name, props} tree
// deserialization engine separate from the main bundle (which imports all
// of @mantine/*), so it can be tested in isolation with Jest without
// loading the whole Mantine library.
export function createBuildElement(components) {
  function buildElement(node) {
    if (node === null || node === undefined) return null;

    switch (node.type) {
      case 'element': {
        const Component = components[node.name];
        if (!Component) {
          throw new Error(`shiny.mantine: unknown component "${node.name}"`);
        }
        return React.createElement(Component, buildProps(node.props));
      }
      case 'html':
        // Static markup generated by htmltools (e.g. tags$h2()). Trusted
        // because it's generated by the app's own author, not user input.
        return React.createElement('div', { dangerouslySetInnerHTML: { __html: node.value } });
      case 'array':
        return node.value.map((child, index) => {
          const element = buildElement(child);
          return React.isValidElement(element) ? React.cloneElement(element, { key: index }) : element;
        });
      case 'object':
        return buildProps(node.value);
      case 'raw':
      default:
        return node.value;
    }
  }

  function buildProps(props) {
    const result = {};
    Object.keys(props || {}).forEach((key) => {
      result[key] = buildElement(props[key]);
    });
    if (typeof result.style === 'string') {
      result.style = styleStringToObject(result.style);
    }
    return result;
  }

  return { buildElement, buildProps };
}
