test_that("generated passthrough components serialize with the expected JS names", {
  expect_equal(Fieldset()$name, "Fieldset")
  expect_equal(DataList()$name, "DataList")
  expect_equal(DataListItem()$name, "DataList.Item")
  expect_equal(DataListItemLabel()$name, "DataList.ItemLabel")
  expect_equal(DataListItemValue()$name, "DataList.ItemValue")
  expect_equal(EmptyState()$name, "EmptyState")
  expect_equal(EmptyStateActions()$name, "EmptyState.Actions")
  expect_equal(EmptyStateDescription()$name, "EmptyState.Description")
  expect_equal(EmptyStateIndicator()$name, "EmptyState.Indicator")
  expect_equal(EmptyStateTitle()$name, "EmptyState.Title")
  expect_equal(Marquee()$name, "Marquee")
  expect_equal(NumberFormatter()$name, "NumberFormatter")
  expect_equal(Pill()$name, "Pill")
  expect_equal(PillGroup()$name, "Pill.Group")
  expect_equal(RollingNumber()$name, "RollingNumber")
  expect_equal(SemiCircleProgress()$name, "SemiCircleProgress")
  expect_equal(TooltipFloating()$name, "TooltipFloating")
  expect_equal(TooltipGroup()$name, "TooltipGroup")
  expect_equal(Typography()$name, "Typography")
  expect_equal(VisuallyHidden()$name, "VisuallyHidden")
})

test_that("generated components forward props through to the JSON tree", {
  el <- Fieldset(legend = "Personal info")
  expect_equal(el$props$legend, list(type = "raw", value = "Personal info"))
})
