# Auto-generated by js/scripts/generate-components.js
# DO NOT EDIT BY HAND — edit MANIFEST there instead and re-run the script.

#' @include mantine-element.R
NULL

#' Mantine AspectRatio
#'
#' Keeps a fixed width/height ratio for its content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname AspectRatio
#' @param ... Props and children. See <https://mantine.dev/core/aspect-ratio/>.
#' @export
AspectRatio <- displayComponent("AspectRatio")

#' Mantine Flex
#'
#' Flexbox container with shorthand props (direction, gap, wrap, align, justify). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Flex
#' @param ... Props and children. See <https://mantine.dev/core/flex/>.
#' @export
Flex <- displayComponent("Flex")

#' Mantine Space
#'
#' Empty horizontal/vertical spacer. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Space
#' @param ... Props and children. See <https://mantine.dev/core/space/>.
#' @export
Space <- displayComponent("Space")

#' Mantine BackgroundImage
#'
#' Container with a background image. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname BackgroundImage
#' @param ... Props and children. See <https://mantine.dev/core/background-image/>.
#' @export
BackgroundImage <- displayComponent("BackgroundImage")

#' Mantine Blockquote
#'
#' Styled quotation block. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Blockquote
#' @param ... Props and children. See <https://mantine.dev/core/blockquote/>.
#' @export
Blockquote <- displayComponent("Blockquote")

#' Mantine Code
#'
#' Inline or block code-styled text. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Code
#' @param ... Props and children. See <https://mantine.dev/core/code/>.
#' @export
Code <- displayComponent("Code")

#' Mantine Highlight
#'
#' Text with highlighted parts (`highlight` prop). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Highlight
#' @param ... Props and children. See <https://mantine.dev/core/highlight/>.
#' @export
Highlight <- displayComponent("Highlight")

#' Mantine List
#'
#' Bulleted/numbered list. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname List
#' @param ... Props and children. See <https://mantine.dev/core/list/>.
#' @export
List <- displayComponent("List")

#' @rdname List
#' @export
ListItem <- displayComponent("List.Item")

#' Mantine Mark
#'
#' Highlighted text (`<mark>` tag). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Mark
#' @param ... Props and children. See <https://mantine.dev/core/mark/>.
#' @export
Mark <- displayComponent("Mark")

#' Mantine CloseButton
#'
#' "x" icon button for closing/removing. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname CloseButton
#' @param ... Props and children. See <https://mantine.dev/core/close-button/>.
#' @export
CloseButton <- displayComponent("CloseButton")

#' Mantine Alert
#'
#' Warning banner with icon/title/color. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Alert
#' @param ... Props and children. See <https://mantine.dev/core/alert/>.
#' @export
Alert <- displayComponent("Alert")

#' Mantine Loader
#'
#' Loading indicator (spinner). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Loader
#' @param ... Props and children. See <https://mantine.dev/core/loader/>.
#' @export
Loader <- displayComponent("Loader")

#' Mantine Skeleton
#'
#' Animated placeholder for loading content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Skeleton
#' @param ... Props and children. See <https://mantine.dev/core/skeleton/>.
#' @export
Skeleton <- displayComponent("Skeleton")

#' Mantine ColorSwatch
#'
#' Small color sample. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ColorSwatch
#' @param ... Props and children. See <https://mantine.dev/core/color-swatch/>.
#' @export
ColorSwatch <- displayComponent("ColorSwatch")

#' Mantine Indicator
#'
#' Badge/dot positioned over an element (e.g. unread notifications). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Indicator
#' @param ... Props and children. See <https://mantine.dev/core/indicator/>.
#' @export
Indicator <- displayComponent("Indicator")

#' Mantine Kbd
#'
#' Keyboard-key-styled text. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Kbd
#' @param ... Props and children. See <https://mantine.dev/core/kbd/>.
#' @export
Kbd <- displayComponent("Kbd")

#' Mantine Spoiler
#'
#' Truncated content with a "show more" toggle. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Spoiler
#' @param ... Props and children. See <https://mantine.dev/core/spoiler/>.
#' @export
Spoiler <- displayComponent("Spoiler")

#' Mantine Timeline
#'
#' Vertical sequence of events. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Timeline
#' @param ... Props and children. See <https://mantine.dev/core/timeline/>.
#' @export
Timeline <- displayComponent("Timeline")

#' @rdname Timeline
#' @export
TimelineItem <- displayComponent("Timeline.Item")

#' Mantine AvatarGroup
#'
#' Groups several overlapping Avatars. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname AvatarGroup
#' @param ... Props and children. See <https://mantine.dev/core/avatar/>.
#' @export
AvatarGroup <- displayComponent("AvatarGroup")

#' Mantine Overlay
#'
#' Semi-transparent layer over some content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Overlay
#' @param ... Props and children. See <https://mantine.dev/core/overlay/>.
#' @export
Overlay <- displayComponent("Overlay")

#' Mantine Breadcrumbs
#'
#' Navigation trail (Home > Section > Page). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Breadcrumbs
#' @param ... Props and children. See <https://mantine.dev/core/breadcrumbs/>.
#' @export
Breadcrumbs <- displayComponent("Breadcrumbs")

#' Mantine Fieldset
#'
#' Groups form inputs under a legend. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Fieldset
#' @param ... Props and children. See <https://mantine.dev/core/fieldset/>.
#' @export
Fieldset <- displayComponent("Fieldset")

#' Mantine DataList
#'
#' Key/value list (definition-list style). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DataList
#' @param ... Props and children. See <https://mantine.dev/core/data-list/>.
#' @export
DataList <- displayComponent("DataList")

#' @rdname DataList
#' @export
DataListItem <- displayComponent("DataList.Item")

#' @rdname DataList
#' @export
DataListItemLabel <- displayComponent("DataList.ItemLabel")

#' @rdname DataList
#' @export
DataListItemValue <- displayComponent("DataList.ItemValue")

#' Mantine EmptyState
#'
#' Placeholder shown when there is no content to display. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname EmptyState
#' @param ... Props and children. See <https://mantine.dev/core/empty-state/>.
#' @export
EmptyState <- displayComponent("EmptyState")

#' @rdname EmptyState
#' @export
EmptyStateActions <- displayComponent("EmptyState.Actions")

#' @rdname EmptyState
#' @export
EmptyStateDescription <- displayComponent("EmptyState.Description")

#' @rdname EmptyState
#' @export
EmptyStateIndicator <- displayComponent("EmptyState.Indicator")

#' @rdname EmptyState
#' @export
EmptyStateTitle <- displayComponent("EmptyState.Title")

#' Mantine Marquee
#'
#' Horizontally scrolling ticker of content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Marquee
#' @param ... Props and children. See <https://mantine.dev/core/marquee/>.
#' @export
Marquee <- displayComponent("Marquee")

#' Mantine NumberFormatter
#'
#' Formats a numeric value as display text (thousand separators, decimals, prefix/suffix). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname NumberFormatter
#' @param ... Props and children. See <https://mantine.dev/core/number-formatter/>.
#' @export
NumberFormatter <- displayComponent("NumberFormatter")

#' Mantine Pill
#'
#' Small rounded tag/chip element. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Pill
#' @param ... Props and children. See <https://mantine.dev/core/pill/>.
#' @export
Pill <- displayComponent("Pill")

#' @rdname Pill
#' @export
PillGroup <- displayComponent("Pill.Group")

#' Mantine RollingNumber
#'
#' Animated rolling/odometer-style number display. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname RollingNumber
#' @param ... Props and children. See <https://mantine.dev/core/rolling-number/>.
#' @export
RollingNumber <- displayComponent("RollingNumber")

#' Mantine SemiCircleProgress
#'
#' Half-circle progress indicator. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname SemiCircleProgress
#' @param ... Props and children. See <https://mantine.dev/core/semi-circle-progress/>.
#' @export
SemiCircleProgress <- displayComponent("SemiCircleProgress")

#' Mantine TooltipFloating
#'
#' Tooltip that follows the cursor instead of anchoring to the target. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname TooltipFloating
#' @param ... Props and children. See <https://mantine.dev/core/tooltip/>.
#' @export
TooltipFloating <- displayComponent("TooltipFloating")

#' Mantine TooltipGroup
#'
#' Shares open/close delay behaviour across a group of Tooltips. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname TooltipGroup
#' @param ... Props and children. See <https://mantine.dev/core/tooltip/>.
#' @export
TooltipGroup <- displayComponent("TooltipGroup")

#' Mantine Typography
#'
#' Applies Mantine's prose/typography styling to arbitrary HTML content (e.g. rendered Markdown). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Typography
#' @param ... Props and children. See <https://mantine.dev/core/typography/>.
#' @export
Typography <- displayComponent("Typography")

#' Mantine VisuallyHidden
#'
#' Visually hides content while keeping it available to screen readers. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname VisuallyHidden
#' @param ... Props and children. See <https://mantine.dev/core/visually-hidden/>.
#' @export
VisuallyHidden <- displayComponent("VisuallyHidden")
