# Auto-generated by js/scripts/generate-components.js
# DO NOT EDIT BY HAND — edit MANIFEST there instead and re-run the script.

#' @include mantine-element.R
NULL

#' Mantine AspectRatio
#'
#' Keeps a fixed width/height ratio for its content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname AspectRatio
#' @param ... Props and children. See <https://mantine.dev/core/aspect-ratio/>.
#' @export
AspectRatio <- displayComponent("AspectRatio")

#' Mantine Flex
#'
#' Flexbox container with shorthand props (direction, gap, wrap, align, justify). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Flex
#' @param ... Props and children. See <https://mantine.dev/core/flex/>.
#' @export
Flex <- displayComponent("Flex")

#' Mantine Space
#'
#' Empty horizontal/vertical spacer. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Space
#' @param ... Props and children. See <https://mantine.dev/core/space/>.
#' @export
Space <- displayComponent("Space")

#' Mantine BackgroundImage
#'
#' Container with a background image. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname BackgroundImage
#' @param ... Props and children. See <https://mantine.dev/core/background-image/>.
#' @export
BackgroundImage <- displayComponent("BackgroundImage")

#' Mantine Blockquote
#'
#' Styled quotation block. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Blockquote
#' @param ... Props and children. See <https://mantine.dev/core/blockquote/>.
#' @export
Blockquote <- displayComponent("Blockquote")

#' Mantine Code
#'
#' Inline or block code-styled text. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Code
#' @param ... Props and children. See <https://mantine.dev/core/code/>.
#' @export
Code <- displayComponent("Code")

#' Mantine Highlight
#'
#' Text with highlighted parts (`highlight` prop). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Highlight
#' @param ... Props and children. See <https://mantine.dev/core/highlight/>.
#' @export
Highlight <- displayComponent("Highlight")

#' Mantine List
#'
#' Bulleted/numbered list. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname List
#' @param ... Props and children. See <https://mantine.dev/core/list/>.
#' @export
List <- displayComponent("List")

#' @rdname List
#' @export
ListItem <- displayComponent("List.Item")

#' Mantine Mark
#'
#' Highlighted text (`<mark>` tag). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Mark
#' @param ... Props and children. See <https://mantine.dev/core/mark/>.
#' @export
Mark <- displayComponent("Mark")

#' Mantine CloseButton
#'
#' "x" icon button for closing/removing. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname CloseButton
#' @param ... Props and children. See <https://mantine.dev/core/close-button/>.
#' @export
CloseButton <- displayComponent("CloseButton")

#' Mantine Alert
#'
#' Warning banner with icon/title/color. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Alert
#' @param ... Props and children. See <https://mantine.dev/core/alert/>.
#' @export
Alert <- displayComponent("Alert")

#' Mantine Loader
#'
#' Loading indicator (spinner). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Loader
#' @param ... Props and children. See <https://mantine.dev/core/loader/>.
#' @export
Loader <- displayComponent("Loader")

#' Mantine Skeleton
#'
#' Animated placeholder for loading content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Skeleton
#' @param ... Props and children. See <https://mantine.dev/core/skeleton/>.
#' @export
Skeleton <- displayComponent("Skeleton")

#' Mantine ColorSwatch
#'
#' Small color sample. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ColorSwatch
#' @param ... Props and children. See <https://mantine.dev/core/color-swatch/>.
#' @export
ColorSwatch <- displayComponent("ColorSwatch")

#' Mantine Indicator
#'
#' Badge/dot positioned over an element (e.g. unread notifications). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Indicator
#' @param ... Props and children. See <https://mantine.dev/core/indicator/>.
#' @export
Indicator <- displayComponent("Indicator")

#' Mantine Kbd
#'
#' Keyboard-key-styled text. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Kbd
#' @param ... Props and children. See <https://mantine.dev/core/kbd/>.
#' @export
Kbd <- displayComponent("Kbd")

#' Mantine Spoiler
#'
#' Truncated content with a "show more" toggle. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Spoiler
#' @param ... Props and children. See <https://mantine.dev/core/spoiler/>.
#' @export
Spoiler <- displayComponent("Spoiler")

#' Mantine Timeline
#'
#' Vertical sequence of events. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Timeline
#' @param ... Props and children. See <https://mantine.dev/core/timeline/>.
#' @export
Timeline <- displayComponent("Timeline")

#' @rdname Timeline
#' @export
TimelineItem <- displayComponent("Timeline.Item")

#' Mantine AvatarGroup
#'
#' Groups several overlapping Avatars. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname AvatarGroup
#' @param ... Props and children. See <https://mantine.dev/core/avatar/>.
#' @export
AvatarGroup <- displayComponent("AvatarGroup")

#' Mantine Overlay
#'
#' Semi-transparent layer over some content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Overlay
#' @param ... Props and children. See <https://mantine.dev/core/overlay/>.
#' @export
Overlay <- displayComponent("Overlay")

#' Mantine Breadcrumbs
#'
#' Navigation trail (Home > Section > Page). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Breadcrumbs
#' @param ... Props and children. See <https://mantine.dev/core/breadcrumbs/>.
#' @export
Breadcrumbs <- displayComponent("Breadcrumbs")

#' Mantine Fieldset
#'
#' Groups form inputs under a legend. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Fieldset
#' @param ... Props and children. See <https://mantine.dev/core/fieldset/>.
#' @export
Fieldset <- displayComponent("Fieldset")

#' Mantine DataList
#'
#' Key/value list (definition-list style). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DataList
#' @param ... Props and children. See <https://mantine.dev/core/data-list/>.
#' @export
DataList <- displayComponent("DataList")

#' @rdname DataList
#' @export
DataListItem <- displayComponent("DataList.Item")

#' @rdname DataList
#' @export
DataListItemLabel <- displayComponent("DataList.ItemLabel")

#' @rdname DataList
#' @export
DataListItemValue <- displayComponent("DataList.ItemValue")

#' Mantine EmptyState
#'
#' Placeholder shown when there is no content to display. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname EmptyState
#' @param ... Props and children. See <https://mantine.dev/core/empty-state/>.
#' @export
EmptyState <- displayComponent("EmptyState")

#' @rdname EmptyState
#' @export
EmptyStateActions <- displayComponent("EmptyState.Actions")

#' @rdname EmptyState
#' @export
EmptyStateDescription <- displayComponent("EmptyState.Description")

#' @rdname EmptyState
#' @export
EmptyStateIndicator <- displayComponent("EmptyState.Indicator")

#' @rdname EmptyState
#' @export
EmptyStateTitle <- displayComponent("EmptyState.Title")

#' Mantine Marquee
#'
#' Horizontally scrolling ticker of content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Marquee
#' @param ... Props and children. See <https://mantine.dev/core/marquee/>.
#' @export
Marquee <- displayComponent("Marquee")

#' Mantine NumberFormatter
#'
#' Formats a numeric value as display text (thousand separators, decimals, prefix/suffix). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname NumberFormatter
#' @param ... Props and children. See <https://mantine.dev/core/number-formatter/>.
#' @export
NumberFormatter <- displayComponent("NumberFormatter")

#' Mantine Pill
#'
#' Small rounded tag/chip element. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Pill
#' @param ... Props and children. See <https://mantine.dev/core/pill/>.
#' @export
Pill <- displayComponent("Pill")

#' @rdname Pill
#' @export
PillGroup <- displayComponent("Pill.Group")

#' Mantine RollingNumber
#'
#' Animated rolling/odometer-style number display. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname RollingNumber
#' @param ... Props and children. See <https://mantine.dev/core/rolling-number/>.
#' @export
RollingNumber <- displayComponent("RollingNumber")

#' Mantine SemiCircleProgress
#'
#' Half-circle progress indicator. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname SemiCircleProgress
#' @param ... Props and children. See <https://mantine.dev/core/semi-circle-progress/>.
#' @export
SemiCircleProgress <- displayComponent("SemiCircleProgress")

#' Mantine TooltipFloating
#'
#' Tooltip that follows the cursor instead of anchoring to the target. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname TooltipFloating
#' @param ... Props and children. See <https://mantine.dev/core/tooltip/>.
#' @export
TooltipFloating <- displayComponent("TooltipFloating")

#' Mantine TooltipGroup
#'
#' Shares open/close delay behaviour across a group of Tooltips. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname TooltipGroup
#' @param ... Props and children. See <https://mantine.dev/core/tooltip/>.
#' @export
TooltipGroup <- displayComponent("TooltipGroup")

#' Mantine Typography
#'
#' Applies Mantine's prose/typography styling to arbitrary HTML content (e.g. rendered Markdown). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Typography
#' @param ... Props and children. See <https://mantine.dev/core/typography/>.
#' @export
Typography <- displayComponent("Typography")

#' Mantine VisuallyHidden
#'
#' Visually hides content while keeping it available to screen readers. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname VisuallyHidden
#' @param ... Props and children. See <https://mantine.dev/core/visually-hidden/>.
#' @export
VisuallyHidden <- displayComponent("VisuallyHidden")

#' Mantine ModalOverlay
#'
#' Dimmed backdrop behind a ModalRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ModalOverlay
#' @param ... Props and children. See <https://mantine.dev/core/modal/>.
#' @export
ModalOverlay <- displayComponent("ModalOverlay")

#' Mantine ModalContent
#'
#' Content box of a ModalRoot() (holds ModalHeader()/ModalBody()). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ModalContent
#' @param ... Props and children. See <https://mantine.dev/core/modal/>.
#' @export
ModalContent <- displayComponent("ModalContent")

#' Mantine ModalHeader
#'
#' Header row of a ModalRoot() (usually ModalTitle() + ModalCloseButton()). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ModalHeader
#' @param ... Props and children. See <https://mantine.dev/core/modal/>.
#' @export
ModalHeader <- displayComponent("ModalHeader")

#' Mantine ModalTitle
#'
#' Title text of a ModalRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ModalTitle
#' @param ... Props and children. See <https://mantine.dev/core/modal/>.
#' @export
ModalTitle <- displayComponent("ModalTitle")

#' Mantine ModalCloseButton
#'
#' Close ("x") button of a ModalRoot() - already wired to its onClose. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ModalCloseButton
#' @param ... Props and children. See <https://mantine.dev/core/modal/>.
#' @export
ModalCloseButton <- displayComponent("ModalCloseButton")

#' Mantine ModalBody
#'
#' Body/content area of a ModalRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ModalBody
#' @param ... Props and children. See <https://mantine.dev/core/modal/>.
#' @export
ModalBody <- displayComponent("ModalBody")

#' Mantine DrawerOverlay
#'
#' Dimmed backdrop behind a DrawerRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DrawerOverlay
#' @param ... Props and children. See <https://mantine.dev/core/drawer/>.
#' @export
DrawerOverlay <- displayComponent("DrawerOverlay")

#' Mantine DrawerContent
#'
#' Content box of a DrawerRoot() (holds DrawerHeader()/DrawerBody()). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DrawerContent
#' @param ... Props and children. See <https://mantine.dev/core/drawer/>.
#' @export
DrawerContent <- displayComponent("DrawerContent")

#' Mantine DrawerHeader
#'
#' Header row of a DrawerRoot() (usually DrawerTitle() + DrawerCloseButton()). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DrawerHeader
#' @param ... Props and children. See <https://mantine.dev/core/drawer/>.
#' @export
DrawerHeader <- displayComponent("DrawerHeader")

#' Mantine DrawerTitle
#'
#' Title text of a DrawerRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DrawerTitle
#' @param ... Props and children. See <https://mantine.dev/core/drawer/>.
#' @export
DrawerTitle <- displayComponent("DrawerTitle")

#' Mantine DrawerCloseButton
#'
#' Close ("x") button of a DrawerRoot() - already wired to its onClose. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DrawerCloseButton
#' @param ... Props and children. See <https://mantine.dev/core/drawer/>.
#' @export
DrawerCloseButton <- displayComponent("DrawerCloseButton")

#' Mantine DrawerBody
#'
#' Body/content area of a DrawerRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname DrawerBody
#' @param ... Props and children. See <https://mantine.dev/core/drawer/>.
#' @export
DrawerBody <- displayComponent("DrawerBody")

#' Mantine PaginationItems
#'
#' Numbered page buttons of a PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationItems
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationItems <- displayComponent("PaginationItems")

#' Mantine PaginationFirst
#'
#' "Go to first page" button of a PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationFirst
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationFirst <- displayComponent("PaginationFirst")

#' Mantine PaginationLast
#'
#' "Go to last page" button of a PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationLast
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationLast <- displayComponent("PaginationLast")

#' Mantine PaginationNext
#'
#' "Go to next page" button of a PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationNext
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationNext <- displayComponent("PaginationNext")

#' Mantine PaginationPrevious
#'
#' "Go to previous page" button of a PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationPrevious
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationPrevious <- displayComponent("PaginationPrevious")

#' Mantine PaginationDots
#'
#' Ellipsis ("...") separator of a PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationDots
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationDots <- displayComponent("PaginationDots")

#' Mantine Input
#'
#' Styled input box (border, focus ring, left/right sections) with no value/onChange management of its own. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Input
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
Input <- displayComponent("Input")

#' Mantine InputBase
#'
#' Like Input(), extended with a few more style-composition options used internally by other inputs. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputBase
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputBase <- displayComponent("InputBase")

#' Mantine InputWrapper
#'
#' Label/description/error/required-asterisk chrome around arbitrary custom content. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputWrapper
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputWrapper <- displayComponent("InputWrapper")

#' Mantine InputLabel
#'
#' Standalone input label, styled like InputWrapper()'s own label. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputLabel
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputLabel <- displayComponent("InputLabel")

#' Mantine InputDescription
#'
#' Standalone input description text, styled like InputWrapper()'s own description. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputDescription
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputDescription <- displayComponent("InputDescription")

#' Mantine InputError
#'
#' Standalone input error text, styled like InputWrapper()'s own error. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputError
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputError <- displayComponent("InputError")

#' Mantine InputPlaceholder
#'
#' Renders its children with input-placeholder styling (dimmed text). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputPlaceholder
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputPlaceholder <- displayComponent("InputPlaceholder")

#' Mantine FocusTrap
#'
#' Traps keyboard focus inside its single child while active. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname FocusTrap
#' @param ... Props and children. See <https://mantine.dev/core/focus-trap/>.
#' @export
FocusTrap <- displayComponent("FocusTrap")

#' Mantine RemoveScroll
#'
#' Prevents the page behind it from scrolling while enabled. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname RemoveScroll
#' @param ... Props and children. See <https://mantine.dev/core/floating/>.
#' @export
RemoveScroll <- displayComponent("RemoveScroll")

#' Mantine MantineThemeProvider
#'
#' Updates the theme object exposed via Mantine's useMantineTheme() hook for custom code - does NOT restyle standard components, see the note in `?MantineThemeProvider`. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname MantineThemeProvider
#' @param ... Props and children. See <https://mantine.dev/core/mantine-provider/>.
#' @export
MantineThemeProvider <- displayComponent("MantineThemeProvider")

#' Mantine CheckIcon
#'
#' The checkmark icon Checkbox()/CheckboxCard() render when checked. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname CheckIcon
#' @param ... Props and children. See <https://mantine.dev/core/checkbox/>.
#' @export
CheckIcon <- displayComponent("CheckIcon")

#' Mantine CloseIcon
#'
#' The "x" icon CloseButton() renders. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname CloseIcon
#' @param ... Props and children. See <https://mantine.dev/core/close-button/>.
#' @export
CloseIcon <- displayComponent("CloseIcon")

#' Mantine AccordionChevron
#'
#' The chevron icon Accordion() renders next to each control. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname AccordionChevron
#' @param ... Props and children. See <https://mantine.dev/core/accordion/>.
#' @export
AccordionChevron <- displayComponent("AccordionChevron")

#' Mantine RadioIcon
#'
#' The dot icon Radio()/RadioCard() render when checked. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname RadioIcon
#' @param ... Props and children. See <https://mantine.dev/core/radio/>.
#' @export
RadioIcon <- displayComponent("RadioIcon")

#' Mantine ActionIconGroupSection
#'
#' Non-interactive section (e.g. a label) placed between grouped ActionIcon()s. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ActionIconGroupSection
#' @param ... Props and children. See <https://mantine.dev/core/action-icon/>.
#' @export
ActionIconGroupSection <- displayComponent("ActionIconGroupSection")

#' Mantine ButtonGroupSection
#'
#' Non-interactive section (e.g. a label) placed between grouped Button()s. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname ButtonGroupSection
#' @param ... Props and children. See <https://mantine.dev/core/button/>.
#' @export
ButtonGroupSection <- displayComponent("ButtonGroupSection")

#' Mantine PillsInput
#'
#' Styled input box for a list of Pill()s plus a text field, the multi-value building block MultiSelect()/TagsInput() use internally. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PillsInput
#' @param ... Props and children. See <https://mantine.dev/core/pills-input/>.
#' @export
PillsInput <- displayComponent("PillsInput")

#' @rdname PillsInput
#' @export
PillsInputField <- displayComponent("PillsInput.Field")

#' Mantine Scroller
#'
#' Horizontally scrollable container with prev/next arrow controls (e.g. for a row of chips/thumbnails). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname Scroller
#' @param ... Props and children. See <https://mantine.dev/core/scroller/>.
#' @export
Scroller <- displayComponent("Scroller")

#' Mantine InputClearButton
#'
#' The "x" clear button Select()/DatePickerInput()/etc. render when clearable, exposed for custom inputs built on Input(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputClearButton
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputClearButton <- displayComponent("InputClearButton")

#' Mantine InputSuccess
#'
#' Standalone input success text, styled like the internal success state of stateful inputs. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname InputSuccess
#' @param ... Props and children. See <https://mantine.dev/core/input/>.
#' @export
InputSuccess <- displayComponent("InputSuccess")

#' Mantine PaginationControl
#'
#' Generic clickable pagination-styled button, for building entirely custom page controls inside PaginationRoot(). Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationControl
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationControl <- displayComponent("PaginationControl")

#' Mantine PaginationLabel
#'
#' The compact "page X of Y" label PaginationRoot() shows in its `layout = "responsive"` mode. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname PaginationLabel
#' @param ... Props and children. See <https://mantine.dev/core/pagination/>.
#' @export
PaginationLabel <- displayComponent("PaginationLabel")

#' Mantine FocusTrapInitialFocus
#'
#' Invisible marker: the first focusable element FocusTrap() should focus, if not the first one in DOM order. Supports `mantineId` for reactive updates via
#' [updateMantineProps()].
#' @rdname FocusTrapInitialFocus
#' @param ... Props and children. See <https://mantine.dev/core/focus-trap/>.
#' @export
FocusTrapInitialFocus <- displayComponent("FocusTrapInitialFocus")
